- button "Filter"
- text: What is your current status?
- textbox "What is your current status? What is your current status? What is your current status? What is your current status? What is your current status? What is your current status? What is your current status?": Some value
- text: light
- button "Filter"
- text: What is your current status?
- textbox "What's happening?": Some value
- text: light_colorblind
- button "Filter"
- text: What is your current status?
- textbox "What's happening?": Some value
- text: light_high_contrast
- button "Filter"
- text: What is your current status?
- textbox "What's happening?": Some value
- text: dark
- button "Filter"
- text: What is your current status?
- textbox "What's happening?": Some value
- text: dark_dimmed
- button "Filter"
- text: What is your current status?
- textbox "What's happening?": Some value
- text: dark_high_contrast
- button "Filter"
- text: What is your current status?
- textbox "What's happening?": Some value
- text: dark_colorblind