- list "List heading":
  - listitem:
    - button "Disabled item Item description" [disabled]
- text: light
- list "List heading":
  - listitem:
    - button "Disabled item Item description" [disabled]
- text: light_colorblind
- list "List heading":
  - listitem:
    - button "Disabled item Item description" [disabled]
- text: light_high_contrast
- list "List heading":
  - listitem:
    - button "Disabled item Item description" [disabled]
- text: dark
- list "List heading":
  - listitem:
    - button "Disabled item Item description" [disabled]
- text: dark_dimmed
- list "List heading":
  - listitem:
    - button "Disabled item Item description" [disabled]
- text: dark_high_contrast
- list "List heading":
  - listitem:
    - button "Disabled item Item description" [disabled]
- text: dark_colorblind