- radio "Battlestar Galactica Battlestar Galactica Battlestar Galactica Battlestar Galactica Battlestar Galactica Battlestar Galactica Battlestar Galactica": bsg
- text: Battlestar Galactica light
- radio: bsg
- text: Battlestar Galactica light_colorblind
- radio: bsg
- text: Battlestar Galactica light_high_contrast
- radio: bsg
- text: Battlestar Galactica dark
- radio: bsg
- text: Battlestar Galactica dark_dimmed
- radio: bsg
- text: Battlestar Galactica dark_high_contrast
- radio: bsg
- text: Battlestar Galactica dark_colorblind