- text: Header Body
- list "Header":
  - listitem: Row one
  - listitem: Row two
  - listitem: Row three
- text: Footer light Header Body
- list "Header":
  - listitem: Row one
  - listitem: Row two
  - listitem: Row three
- text: Footer light_colorblind Header Body
- list "Header":
  - listitem: Row one
  - listitem: Row two
  - listitem: Row three
- text: Footer light_high_contrast Header Body
- list "Header":
  - listitem: Row one
  - listitem: Row two
  - listitem: Row three
- text: Footer dark Header Body
- list "Header":
  - listitem: Row one
  - listitem: Row two
  - listitem: Row three
- text: Footer dark_dimmed Header Body
- list "Header":
  - listitem: Row one
  - listitem: Row two
  - listitem: Row three
- text: Footer dark_high_contrast Header Body
- list "Header":
  - listitem: Row one
  - listitem: Row two
  - listitem: Row three
- text: Footer dark_colorblind