- paragraph: Did you know? Comments can be edited.
- button "Edit"
- text: light
- paragraph: Did you know? Comments can be edited.
- button "Edit"
- text: light_colorblind
- paragraph: Did you know? Comments can be edited.
- button "Edit"
- text: light_high_contrast
- paragraph: Did you know? Comments can be edited.
- button "Edit"
- text: dark
- paragraph: Did you know? Comments can be edited.
- button "Edit"
- text: dark_dimmed
- paragraph: Did you know? Comments can be edited.
- button "Edit"
- text: dark_high_contrast
- paragraph: Did you know? Comments can be edited.
- button "Edit"
- text: dark_colorblind