---
EnableDefaultLinters: true
linters:
  ButtonComponentMigrationCounter:
    enabled: true
  FlashComponentMigrationCounter:
    enabled: true
  LabelComponentMigrationCounter:
    enabled: true
  TwoColumnLayouts:
    enabled: true
  Rubocop:
    enabled: true
    rubocop_config:
      inherit_from:
        - lib/rubocop/config/default.yml
