---
EnableDefaultLinters: true
linters:
  ButtonComponentMigrationCounter:
    enabled: true
  FlashComponentMigrationCounter:
    enabled: true
  LabelComponentMigrationCounter:
    enabled: true
  Rubocop:
    enabled: true
    rubocop_config:
      inherit_from:
        - lib/rubocop/config/default.yml
      Primer/DeprecatedComponents:
        Enabled: true
        Exclude:
          - app/components/primer/layout_component.html.erb
