---
EnableDefaultLinters: true
linters:
  DeprecatedComponentsCounter:
    enabled: true
  ButtonComponentMigrationCounter:
    enabled: true
  FlashMigrationCounter:
    enabled: true
  LabelComponentMigrationCounter:
    enabled: true
  GitHub::Accessibility::AvoidBothDisabledAndAriaDisabled:
    enabled: true
  GitHub::Accessibility::AvoidGenericLinkTextCounter:
    enabled: true
  GitHub::Accessibility::DisabledAttributeCounter:
    enabled: true
  GitHub::Accessibility::IframeHasTitle:
    enabled: true
  GitHub::Accessibility::ImageHasAlt:
    enabled: true
  GitHub::Accessibility::LinkHasHrefCounter:
    enabled: true
  GitHub::Accessibility::NoAriaLabelMisuseCounter:
    enabled: true
  GitHub::Accessibility::NoPositiveTabIndex:
    enabled: true
  GitHub::Accessibility::NoRedundantImageAlt:
    enabled: true
  GitHub::Accessibility::NoTitleAttributeCounter:
    enabled: true
  GitHub::Accessibility::SvgHasAccessibleTextCounter:
    enabled: true
  Rubocop:
    enabled: true
    rubocop_config:
      inherit_from:
        - lib/rubocop/config/default.yml
      AllCops:
        DisabledByDefault: true
      Primer/DeprecatedComponents:
        Enabled: true
        Exclude:
          - app/components/primer/layout_component.html.erb
