---
EnableDefaultLinters: true
inherit_gem:
  erblint-github:
    - config/accessibility.yml
linters:
  DeprecatedComponentsCounter:
    enabled: true
  ButtonComponentMigrationCounter:
    enabled: true
  FlashMigrationCounter:
    enabled: true
  LabelComponentMigrationCounter:
    enabled: true
  Rubocop:
    enabled: true
    rubocop_config:
      inherit_from:
        - lib/rubocop/config/default.yml
      AllCops:
        DisabledByDefault: true
      Primer/DeprecatedComponents:
        Enabled: false
        Exclude:
          - app/components/primer/layout_component.html.erb
