---
EnableDefaultLinters: true
linters:
  ButtonComponentMigrationCounter:
    enabled: true
  FlashMigrationCounter:
    enabled: true
  LabelComponentMigrationCounter:
    enabled: true
  Rubocop:
    enabled: true
    rubocop_config:
      inherit_from:
        - lib/rubocop/config/default.yml
      inherit_gem:
        rubocop-github:
          - config/default_edge.yml
          - config/rails_edge.yml
      Primer/DeprecatedComponents:
        Enabled: true
        Exclude:
          - app/components/primer/layout_component.html.erb
