inherit_gem:
  rubocop-github:
    - config/default_edge.yml
    - config/rails_edge.yml
require:
  - rubocop/cop/primer

AllCops:
  NewCops: enable
  Exclude:
    - "test/tmp/**/*"
    - "demo/**/*"
    - "**/vendor/**/*"
    - "**/node_modules/**/*"
    - "test/previews/docs/**/*"
  TargetRubyVersion: 2.6

Style/ClassAndModuleChildren:
  Enabled: true
  Exclude:
    - "test/**/*"

Style/Documentation:
  Enabled: true
  Exclude:
    - "test/**/*"

Naming/MethodParameterName:
  Enabled: true
  MinNameLength: 2

Rails/RefuteMethods:
  Enabled: false

Rails/FilePath:
  EnforcedStyle: arguments

Style/MultipleComparison:
  Enabled: true
  Exclude:
    - lib/primer/classify.rb

Rails/RakeEnvironment:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Rails/OutputSafety:
  Enabled: true

Style/AsciiComments:
  Enabled: false

Primer/NoTagMemoize:
  Enabled: true
  Include:
    - "app/components/**/*"

Primer/SystemArgumentInsteadOfClass:
  Enabled: true

Lint/MissingSuper:
  Enabled: false

Naming/VariableNumber:
  Enabled: false

Primer/DeprecatedArguments:
  Enabled: false

Primer/DeprecatedLayoutComponent:
  Enabled: false

Primer/ComponentNameMigration:
  Enabled: true
  Severity: info
  Exclude:
    - "test/**/*"

Primer/DeprecatedComponents:
  Enabled: false

Primer/DeprecatedLabelVariants:
  Enabled: true
  Exclude:
    - "test/**/*"

Primer/TestSelector:
  Enabled: true
