- text: My text field
- textbox "My text field My text field My text field My text field My text field My text field My text field"
- text: An error occurred! light My text field
- textbox
- text: An error occurred! light_colorblind My text field
- textbox
- text: An error occurred! light_high_contrast My text field
- textbox
- text: An error occurred! dark My text field
- textbox
- text: An error occurred! dark_dimmed My text field
- textbox
- text: An error occurred! dark_high_contrast My text field
- textbox
- text: An error occurred! dark_colorblind