- 'button "Item: Item 1"'
- separator
- button "Submit"
- text: light
- 'button "Item: Item 1"'
- separator
- button "Submit"
- text: light_colorblind
- 'button "Item: Item 1"'
- separator
- button "Submit"
- text: light_high_contrast
- 'button "Item: Item 1"'
- separator
- button "Submit"
- text: dark
- 'button "Item: Item 1"'
- separator
- button "Submit"
- text: dark_dimmed
- 'button "Item: Item 1"'
- separator
- button "Submit"
- text: dark_high_contrast
- 'button "Item: Item 1"'
- separator
- button "Submit"
- text: dark_colorblind