- group "Cool places":
  - text: Cool places
  - checkbox "Lopez Island Lopez Island Lopez Island Lopez Island Lopez Island Lopez Island Lopez Island": lopez
  - text: Lopez Island Vacation getaway
  - checkbox "Bellevue Bellevue Bellevue Bellevue Bellevue Bellevue Bellevue": bellevue
  - text: Bellevue Beautiful view
  - checkbox "Seattle Seattle Seattle Seattle Seattle Seattle Seattle": seattle
  - text: Seattle The emerald city
- text: light
- group "Cool places":
  - text: Cool places
  - checkbox: lopez
  - text: Lopez Island Vacation getaway
  - checkbox: bellevue
  - text: Bellevue Beautiful view
  - checkbox: seattle
  - text: Seattle The emerald city
- text: light_colorblind
- group "Cool places":
  - text: Cool places
  - checkbox: lopez
  - text: Lopez Island Vacation getaway
  - checkbox: bellevue
  - text: Bellevue Beautiful view
  - checkbox: seattle
  - text: Seattle The emerald city
- text: light_high_contrast
- group "Cool places":
  - text: Cool places
  - checkbox: lopez
  - text: Lopez Island Vacation getaway
  - checkbox: bellevue
  - text: Bellevue Beautiful view
  - checkbox: seattle
  - text: Seattle The emerald city
- text: dark
- group "Cool places":
  - text: Cool places
  - checkbox: lopez
  - text: Lopez Island Vacation getaway
  - checkbox: bellevue
  - text: Bellevue Beautiful view
  - checkbox: seattle
  - text: Seattle The emerald city
- text: dark_dimmed
- group "Cool places":
  - text: Cool places
  - checkbox: lopez
  - text: Lopez Island Vacation getaway
  - checkbox: bellevue
  - text: Bellevue Beautiful view
  - checkbox: seattle
  - text: Seattle The emerald city
- text: dark_high_contrast
- group "Cool places":
  - text: Cool places
  - checkbox: lopez
  - text: Lopez Island Vacation getaway
  - checkbox: bellevue
  - text: Bellevue Beautiful view
  - checkbox: seattle
  - text: Seattle The emerald city
- text: dark_colorblind