- text: File view Change the way the file is viewed
- list "File view":
  - listitem:
    - button "Preview"
  - listitem:
    - button "Raw"
  - listitem:
    - button "Blame"
- text: light File view Change the way the file is viewed
- list "File view":
  - listitem:
    - button "Preview"
  - listitem:
    - button "Raw"
  - listitem:
    - button "Blame"
- text: light_colorblind File view Change the way the file is viewed
- list "File view":
  - listitem:
    - button "Preview"
  - listitem:
    - button "Raw"
  - listitem:
    - button "Blame"
- text: light_high_contrast File view Change the way the file is viewed
- list "File view":
  - listitem:
    - button "Preview"
  - listitem:
    - button "Raw"
  - listitem:
    - button "Blame"
- text: dark File view Change the way the file is viewed
- list "File view":
  - listitem:
    - button "Preview"
  - listitem:
    - button "Raw"
  - listitem:
    - button "Blame"
- text: dark_dimmed File view Change the way the file is viewed
- list "File view":
  - listitem:
    - button "Preview"
  - listitem:
    - button "Raw"
  - listitem:
    - button "Blame"
- text: dark_high_contrast File view Change the way the file is viewed
- list "File view":
  - listitem:
    - button "Preview"
  - listitem:
    - button "Raw"
  - listitem:
    - button "Blame"
- text: dark_colorblind