- list:
  - listitem: Default
  - listitem: Neutral
  - listitem: Info
  - listitem: Warning
- text: light
- list:
  - listitem: Default
  - listitem: Neutral
  - listitem: Info
  - listitem: Warning
- text: light_colorblind
- list:
  - listitem: Default
  - listitem: Neutral
  - listitem: Info
  - listitem: Warning
- text: light_high_contrast
- list:
  - listitem: Default
  - listitem: Neutral
  - listitem: Info
  - listitem: Warning
- text: dark
- list:
  - listitem: Default
  - listitem: Neutral
  - listitem: Info
  - listitem: Warning
- text: dark_dimmed
- list:
  - listitem: Default
  - listitem: Neutral
  - listitem: Info
  - listitem: Warning
- text: dark_high_contrast
- list:
  - listitem: Default
  - listitem: Neutral
  - listitem: Info
  - listitem: Warning
- text: dark_colorblind