- list "Billing duration":
  - listitem:
    - button "Monthly"
  - listitem:
    - button "Yearly -8%"
- text: light
- list "Billing duration":
  - listitem:
    - button "Monthly"
  - listitem:
    - button "Yearly -8%"
- text: light_colorblind
- list "Billing duration":
  - listitem:
    - button "Monthly"
  - listitem:
    - button "Yearly -8%"
- text: light_high_contrast
- list "Billing duration":
  - listitem:
    - button "Monthly"
  - listitem:
    - button "Yearly -8%"
- text: dark
- list "Billing duration":
  - listitem:
    - button "Monthly"
  - listitem:
    - button "Yearly -8%"
- text: dark_dimmed
- list "Billing duration":
  - listitem:
    - button "Monthly"
  - listitem:
    - button "Yearly -8%"
- text: dark_high_contrast
- list "Billing duration":
  - listitem:
    - button "Monthly"
  - listitem:
    - button "Yearly -8%"
- text: dark_colorblind