- heading "Action List" [level=3]
- list "Action List":
  - listitem:
    - link "Item one"
  - listitem:
    - link "Item two"
  - listitem:
    - link "Item three"
- text: light
- heading "Action List" [level=3]
- list "Action List":
  - listitem:
    - link "Item one"
  - listitem:
    - link "Item two"
  - listitem:
    - link "Item three"
- text: light_colorblind
- heading "Action List" [level=3]
- list "Action List":
  - listitem:
    - link "Item one"
  - listitem:
    - link "Item two"
  - listitem:
    - link "Item three"
- text: light_high_contrast
- heading "Action List" [level=3]
- list "Action List":
  - listitem:
    - link "Item one"
  - listitem:
    - link "Item two"
  - listitem:
    - link "Item three"
- text: dark
- heading "Action List" [level=3]
- list "Action List":
  - listitem:
    - link "Item one"
  - listitem:
    - link "Item two"
  - listitem:
    - link "Item three"
- text: dark_dimmed
- heading "Action List" [level=3]
- list "Action List":
  - listitem:
    - link "Item one"
  - listitem:
    - link "Item two"
  - listitem:
    - link "Item three"
- text: dark_high_contrast
- heading "Action List" [level=3]
- list "Action List":
  - listitem:
    - link "Item one"
  - listitem:
    - link "Item two"
  - listitem:
    - link "Item three"
- text: dark_colorblind