- navigation "Breadcrumb":
  - list:
    - listitem:
      - link "Breadcrumb Item 1"
    - listitem:
      - link "Breadcrumb Item 2"
- text: light
- navigation "Breadcrumb":
  - list:
    - listitem:
      - link "Breadcrumb Item 1"
    - listitem:
      - link "Breadcrumb Item 2"
- text: light_colorblind
- navigation "Breadcrumb":
  - list:
    - listitem:
      - link "Breadcrumb Item 1"
    - listitem:
      - link "Breadcrumb Item 2"
- text: light_high_contrast
- navigation "Breadcrumb":
  - list:
    - listitem:
      - link "Breadcrumb Item 1"
    - listitem:
      - link "Breadcrumb Item 2"
- text: dark
- navigation "Breadcrumb":
  - list:
    - listitem:
      - link "Breadcrumb Item 1"
    - listitem:
      - link "Breadcrumb Item 2"
- text: dark_dimmed
- navigation "Breadcrumb":
  - list:
    - listitem:
      - link "Breadcrumb Item 1"
    - listitem:
      - link "Breadcrumb Item 2"
- text: dark_high_contrast
- navigation "Breadcrumb":
  - list:
    - listitem:
      - link "Breadcrumb Item 1"
    - listitem:
      - link "Breadcrumb Item 2"
- text: dark_colorblind