- text: First name
- textbox "First name First name First name First name First name First name First name"
- text: What you go by.
- paragraph: Hello world
- text: light First name
- textbox
- text: What you go by.
- paragraph: Hello world
- text: light_colorblind First name
- textbox
- text: What you go by.
- paragraph: Hello world
- text: light_high_contrast First name
- textbox
- text: What you go by.
- paragraph: Hello world
- text: dark First name
- textbox
- text: What you go by.
- paragraph: Hello world
- text: dark_dimmed First name
- textbox
- text: What you go by.
- paragraph: Hello world
- text: dark_high_contrast First name
- textbox
- text: What you go by.
- paragraph: Hello world
- text: dark_colorblind