- button
- text: light
- button
- text: light_colorblind
- button
- text: light_high_contrast
- button
- text: dark
- button
- text: dark_dimmed
- button
- text: dark_high_contrast
- button
- text: dark_colorblind