- heading "It looks like we have discovered a vulnerability" [level=2]
- link "Fix issue"
- text: light
- heading "It looks like we have discovered a vulnerability" [level=2]
- link "Fix issue"
- text: light_colorblind
- heading "It looks like we have discovered a vulnerability" [level=2]
- link "Fix issue"
- text: light_high_contrast
- heading "It looks like we have discovered a vulnerability" [level=2]
- link "Fix issue"
- text: dark
- heading "It looks like we have discovered a vulnerability" [level=2]
- link "Fix issue"
- text: dark_dimmed
- heading "It looks like we have discovered a vulnerability" [level=2]
- link "Fix issue"
- text: dark_high_contrast
- heading "It looks like we have discovered a vulnerability" [level=2]
- link "Fix issue"
- text: dark_colorblind