- text: Ultimate answer
- textbox "Ultimate answer Ultimate answer Ultimate answer Ultimate answer Ultimate answer Ultimate answer Ultimate answer"
- text: The answer to life, the universe, and everything light Ultimate answer
- textbox
- text: The answer to life, the universe, and everything light_colorblind Ultimate answer
- textbox
- text: The answer to life, the universe, and everything light_high_contrast Ultimate answer
- textbox
- text: The answer to life, the universe, and everything dark Ultimate answer
- textbox
- text: The answer to life, the universe, and everything dark_dimmed Ultimate answer
- textbox
- text: The answer to life, the universe, and everything dark_high_contrast Ultimate answer
- textbox
- text: The answer to life, the universe, and everything dark_colorblind