- img "octocat"
- text: Success! light
- img "octocat"
- text: Success! light_colorblind
- img "octocat"
- text: Success! light_high_contrast
- img "octocat"
- text: Success! dark
- img "octocat"
- text: Success! dark_dimmed
- img "octocat"
- text: Success! dark_high_contrast
- img "octocat"
- text: Success! dark_colorblind