- text: My text field
- textbox "My text field My text field My text field My text field My text field My text field My text field"
- text: minute light My text field
- textbox
- text: minute light_colorblind My text field
- textbox
- text: minute light_high_contrast My text field
- textbox
- text: minute dark My text field
- textbox
- text: minute dark_dimmed My text field
- textbox
- text: minute dark_high_contrast My text field
- textbox
- text: minute dark_colorblind