- button "Button"
- button "Button"
- button "Button"
- button "Button ( )": Button ()
- button "Button ( )": Button ()
- button "Button ( )": Button ()
- button "Button with tooltip"
- text: light
- button "Button"
- button "Button"
- button "Button"
- button "Button ( )": Button ()
- button "Button ( )": Button ()
- button "Button ( )": Button ()
- button "Button with tooltip"
- text: light_colorblind
- button "Button"
- button "Button"
- button "Button"
- button "Button ( )": Button ()
- button "Button ( )": Button ()
- button "Button ( )": Button ()
- button "Button with tooltip"
- text: light_high_contrast
- button "Button"
- button "Button"
- button "Button"
- button "Button ( )": Button ()
- button "Button ( )": Button ()
- button "Button ( )": Button ()
- button "Button with tooltip"
- text: dark
- button "Button"
- button "Button"
- button "Button"
- button "Button ( )": Button ()
- button "Button ( )": Button ()
- button "Button ( )": Button ()
- button "Button with tooltip"
- text: dark_dimmed
- button "Button"
- button "Button"
- button "Button"
- button "Button ( )": Button ()
- button "Button ( )": Button ()
- button "Button ( )": Button ()
- button "Button with tooltip"
- text: dark_high_contrast
- button "Button"
- button "Button"
- button "Button"
- button "Button ( )": Button ()
- button "Button ( )": Button ()
- button "Button ( )": Button ()
- button "Button with tooltip"
- text: dark_colorblind