- text: Loading
- heading "Mirroring your repository" [level=2]
- paragraph: We’re currently mirroring this repository. It should take anywhere from a few minutes to a couple of hours depending on the size of the repository.
- text: light Loading
- heading "Mirroring your repository" [level=2]
- paragraph: We’re currently mirroring this repository. It should take anywhere from a few minutes to a couple of hours depending on the size of the repository.
- text: light_colorblind Loading
- heading "Mirroring your repository" [level=2]
- paragraph: We’re currently mirroring this repository. It should take anywhere from a few minutes to a couple of hours depending on the size of the repository.
- text: light_high_contrast Loading
- heading "Mirroring your repository" [level=2]
- paragraph: We’re currently mirroring this repository. It should take anywhere from a few minutes to a couple of hours depending on the size of the repository.
- text: dark Loading
- heading "Mirroring your repository" [level=2]
- paragraph: We’re currently mirroring this repository. It should take anywhere from a few minutes to a couple of hours depending on the size of the repository.
- text: dark_dimmed Loading
- heading "Mirroring your repository" [level=2]
- paragraph: We’re currently mirroring this repository. It should take anywhere from a few minutes to a couple of hours depending on the size of the repository.
- text: dark_high_contrast Loading
- heading "Mirroring your repository" [level=2]
- paragraph: We’re currently mirroring this repository. It should take anywhere from a few minutes to a couple of hours depending on the size of the repository.
- text: dark_colorblind