- link "January 1, 2020 00:00on Jan 1, 2020"
- text: light
- link "January 1, 2020 00:00on Jan 1, 2020"
- text: light_colorblind
- link "January 1, 2020 00:00on Jan 1, 2020"
- text: light_high_contrast
- link "January 1, 2020 00:00on Jan 1, 2020"
- text: dark
- link "January 1, 2020 00:00on Jan 1, 2020"
- text: dark_dimmed
- link "January 1, 2020 00:00on Jan 1, 2020"
- text: dark_high_contrast
- link "January 1, 2020 00:00on Jan 1, 2020"
- text: dark_colorblind