- text: Will have error
- textbox "Will have error Will have error Will have error Will have error Will have error Will have error Will have error"
- text: Every time this checks with the server, it returns an error Will not error
- textbox "Will not error Will not error Will not error Will not error Will not error Will not error Will not error"
- text: This message will go away once you type something Will not have an error when it checks the server Random error or success
- textbox "Random error or success Random error or success Random error or success Random error or success Random error or success Random error or success Random error or success"
- text: Server checks will randomly respond with errors or success light Will have error
- textbox
- text: Every time this checks with the server, it returns an error Will not error
- textbox
- text: This message will go away once you type something Will not have an error when it checks the server Random error or success
- textbox
- text: Server checks will randomly respond with errors or success light_colorblind Will have error
- textbox
- text: Every time this checks with the server, it returns an error Will not error
- textbox
- text: This message will go away once you type something Will not have an error when it checks the server Random error or success
- textbox
- text: Server checks will randomly respond with errors or success light_high_contrast Will have error
- textbox
- text: Every time this checks with the server, it returns an error Will not error
- textbox
- text: This message will go away once you type something Will not have an error when it checks the server Random error or success
- textbox
- text: Server checks will randomly respond with errors or success dark Will have error
- textbox
- text: Every time this checks with the server, it returns an error Will not error
- textbox
- text: This message will go away once you type something Will not have an error when it checks the server Random error or success
- textbox
- text: Server checks will randomly respond with errors or success dark_dimmed Will have error
- textbox
- text: Every time this checks with the server, it returns an error Will not error
- textbox
- text: This message will go away once you type something Will not have an error when it checks the server Random error or success
- textbox
- text: Server checks will randomly respond with errors or success dark_high_contrast Will have error
- textbox
- text: Every time this checks with the server, it returns an error Will not error
- textbox
- text: This message will go away once you type something Will not have an error when it checks the server Random error or success
- textbox
- text: Server checks will randomly respond with errors or success dark_colorblind