- group: Button
- text: light
- group: Button
- text: light_colorblind
- group: Button
- text: light_high_contrast
- group: Button
- text: dark
- group: Button
- text: dark_dimmed
- group: Button
- text: dark_high_contrast
- group: Button
- text: dark_colorblind