- navigation "Default with nav element":
  - list:
    - listitem:
      - link "Item 1"
    - listitem:
      - link "Item 2"
    - listitem:
      - link "Item 3"
  - button "Button"
- text: light
- navigation "Default with nav element":
  - list:
    - listitem:
      - link "Item 1"
    - listitem:
      - link "Item 2"
    - listitem:
      - link "Item 3"
  - button "Button"
- text: light_colorblind
- navigation "Default with nav element":
  - list:
    - listitem:
      - link "Item 1"
    - listitem:
      - link "Item 2"
    - listitem:
      - link "Item 3"
  - button "Button"
- text: light_high_contrast
- navigation "Default with nav element":
  - list:
    - listitem:
      - link "Item 1"
    - listitem:
      - link "Item 2"
    - listitem:
      - link "Item 3"
  - button "Button"
- text: dark
- navigation "Default with nav element":
  - list:
    - listitem:
      - link "Item 1"
    - listitem:
      - link "Item 2"
    - listitem:
      - link "Item 3"
  - button "Button"
- text: dark_dimmed
- navigation "Default with nav element":
  - list:
    - listitem:
      - link "Item 1"
    - listitem:
      - link "Item 2"
    - listitem:
      - link "Item 3"
  - button "Button"
- text: dark_high_contrast
- navigation "Default with nav element":
  - list:
    - listitem:
      - link "Item 1"
    - listitem:
      - link "Item 2"
    - listitem:
      - link "Item 3"
  - button "Button"
- text: dark_colorblind