- text: Cool cities
- combobox "Cool cities Cool cities Cool cities Cool cities Cool cities Cool cities Cool cities":
  - option [selected]
  - option "Lopez Island"
  - option "Bellevue"
  - option "Seattle"
- text: Select your favorite! Places you've been
- listbox "Places you've been Places you've been Places you've been Places you've been Places you've been Places you've been Places you've been":
  - option "Lima, Peru"
  - option "Tokyo, Japan"
  - option "Reykjavík, Iceland"
  - option "Chiang Mai, Thailand"
  - option "Queenstown, New Zealand"
- text: Select all that apply
- button "Submit"
- text: light Cool cities
- combobox:
  - option [selected]
  - option "Lopez Island"
  - option "Bellevue"
  - option "Seattle"
- text: Select your favorite! Places you've been
- listbox:
  - option "Lima, Peru"
  - option "Tokyo, Japan"
  - option "Reykjavík, Iceland"
  - option "Chiang Mai, Thailand"
  - option "Queenstown, New Zealand"
- text: Select all that apply
- button "Submit"
- text: light_colorblind Cool cities
- combobox:
  - option [selected]
  - option "Lopez Island"
  - option "Bellevue"
  - option "Seattle"
- text: Select your favorite! Places you've been
- listbox:
  - option "Lima, Peru"
  - option "Tokyo, Japan"
  - option "Reykjavík, Iceland"
  - option "Chiang Mai, Thailand"
  - option "Queenstown, New Zealand"
- text: Select all that apply
- button "Submit"
- text: light_high_contrast Cool cities
- combobox:
  - option [selected]
  - option "Lopez Island"
  - option "Bellevue"
  - option "Seattle"
- text: Select your favorite! Places you've been
- listbox:
  - option "Lima, Peru"
  - option "Tokyo, Japan"
  - option "Reykjavík, Iceland"
  - option "Chiang Mai, Thailand"
  - option "Queenstown, New Zealand"
- text: Select all that apply
- button "Submit"
- text: dark Cool cities
- combobox:
  - option [selected]
  - option "Lopez Island"
  - option "Bellevue"
  - option "Seattle"
- text: Select your favorite! Places you've been
- listbox:
  - option "Lima, Peru"
  - option "Tokyo, Japan"
  - option "Reykjavík, Iceland"
  - option "Chiang Mai, Thailand"
  - option "Queenstown, New Zealand"
- text: Select all that apply
- button "Submit"
- text: dark_dimmed Cool cities
- combobox:
  - option [selected]
  - option "Lopez Island"
  - option "Bellevue"
  - option "Seattle"
- text: Select your favorite! Places you've been
- listbox:
  - option "Lima, Peru"
  - option "Tokyo, Japan"
  - option "Reykjavík, Iceland"
  - option "Chiang Mai, Thailand"
  - option "Queenstown, New Zealand"
- text: Select all that apply
- button "Submit"
- text: dark_high_contrast Cool cities
- combobox:
  - option [selected]
  - option "Lopez Island"
  - option "Bellevue"
  - option "Seattle"
- text: Select your favorite! Places you've been
- listbox:
  - option "Lima, Peru"
  - option "Tokyo, Japan"
  - option "Reykjavík, Iceland"
  - option "Chiang Mai, Thailand"
  - option "Queenstown, New Zealand"
- text: Select all that apply
- button "Submit"
- text: dark_colorblind