- radio "Battlestar Galactica Battlestar Galactica Battlestar Galactica Battlestar Galactica Battlestar Galactica Battlestar Galactica Battlestar Galactica" [disabled]: bsg4
- text: Battlestar Galactica light
- radio [disabled]: bsg4
- text: Battlestar Galactica light_colorblind
- radio [disabled]: bsg4
- text: Battlestar Galactica light_high_contrast
- radio [disabled]: bsg4
- text: Battlestar Galactica dark
- radio [disabled]: bsg4
- text: Battlestar Galactica dark_dimmed
- radio [disabled]: bsg4
- text: Battlestar Galactica dark_high_contrast
- radio [disabled]: bsg4
- text: Battlestar Galactica dark_colorblind