- navigation "With icons and counters":
  - list:
    - listitem:
      - link "Item 1 5"
    - listitem:
      - link "Item 2 10"
    - listitem:
      - link "Item 3 15"
- text: light
- navigation "With icons and counters":
  - list:
    - listitem:
      - link "Item 1 5"
    - listitem:
      - link "Item 2 10"
    - listitem:
      - link "Item 3 15"
- text: light_colorblind
- navigation "With icons and counters":
  - list:
    - listitem:
      - link "Item 1 5"
    - listitem:
      - link "Item 2 10"
    - listitem:
      - link "Item 3 15"
- text: light_high_contrast
- navigation "With icons and counters":
  - list:
    - listitem:
      - link "Item 1 5"
    - listitem:
      - link "Item 2 10"
    - listitem:
      - link "Item 3 15"
- text: dark
- navigation "With icons and counters":
  - list:
    - listitem:
      - link "Item 1 5"
    - listitem:
      - link "Item 2 10"
    - listitem:
      - link "Item 3 15"
- text: dark_dimmed
- navigation "With icons and counters":
  - list:
    - listitem:
      - link "Item 1 5"
    - listitem:
      - link "Item 2 10"
    - listitem:
      - link "Item 3 15"
- text: dark_high_contrast
- navigation "With icons and counters":
  - list:
    - listitem:
      - link "Item 1 5"
    - listitem:
      - link "Item 2 10"
    - listitem:
      - link "Item 3 15"
- text: dark_colorblind