- list "File view":
  - listitem:
    - link "Preview"
  - listitem:
    - link "Raw"
  - listitem:
    - link "Blame"
- text: light
- list "File view":
  - listitem:
    - link "Preview"
  - listitem:
    - link "Raw"
  - listitem:
    - link "Blame"
- text: light_colorblind
- list "File view":
  - listitem:
    - link "Preview"
  - listitem:
    - link "Raw"
  - listitem:
    - link "Blame"
- text: light_high_contrast
- list "File view":
  - listitem:
    - link "Preview"
  - listitem:
    - link "Raw"
  - listitem:
    - link "Blame"
- text: dark
- list "File view":
  - listitem:
    - link "Preview"
  - listitem:
    - link "Raw"
  - listitem:
    - link "Blame"
- text: dark_dimmed
- list "File view":
  - listitem:
    - link "Preview"
  - listitem:
    - link "Raw"
  - listitem:
    - link "Blame"
- text: dark_high_contrast
- list "File view":
  - listitem:
    - link "Preview"
  - listitem:
    - link "Raw"
  - listitem:
    - link "Blame"
- text: dark_colorblind