- text: A Heading A description with actions
- button "An action"
- text: light A Heading A description with actions
- button "An action"
- text: light_colorblind A Heading A description with actions
- button "An action"
- text: light_high_contrast A Heading A description with actions
- button "An action"
- text: dark A Heading A description with actions
- button "An action"
- text: dark_dimmed A Heading A description with actions
- button "An action"
- text: dark_high_contrast A Heading A description with actions
- button "An action"
- text: dark_colorblind