- list "List heading":
  - listitem:
    - link "Item with trailing visual"
- text: light
- list "List heading":
  - listitem:
    - link "Item with trailing visual"
- text: light_colorblind
- list "List heading":
  - listitem:
    - link "Item with trailing visual"
- text: light_high_contrast
- list "List heading":
  - listitem:
    - link "Item with trailing visual"
- text: dark
- list "List heading":
  - listitem:
    - link "Item with trailing visual"
- text: dark_dimmed
- list "List heading":
  - listitem:
    - link "Item with trailing visual"
- text: dark_high_contrast
- list "List heading":
  - listitem:
    - link "Item with trailing visual"
- text: dark_colorblind