- button "This is a button styled to look like a link that wraps like a link"
- text: light
- button "This is a button styled to look like a link that wraps like a link"
- text: light_colorblind
- button "This is a button styled to look like a link that wraps like a link"
- text: light_high_contrast
- button "This is a button styled to look like a link that wraps like a link"
- text: dark
- button "This is a button styled to look like a link that wraps like a link"
- text: dark_dimmed
- button "This is a button styled to look like a link that wraps like a link"
- text: dark_high_contrast
- button "This is a button styled to look like a link that wraps like a link"
- text: dark_colorblind