- navigation "With icons and counters":
  - list:
    - listitem:
      - link "Stars 10"
    - listitem:
      - link "Sponsors 14"
    - listitem:
      - link "Bookmarks 7"
- text: light
- navigation "With icons and counters":
  - list:
    - listitem:
      - link "Stars 10"
    - listitem:
      - link "Sponsors 14"
    - listitem:
      - link "Bookmarks 7"
- text: light_colorblind
- navigation "With icons and counters":
  - list:
    - listitem:
      - link "Stars 10"
    - listitem:
      - link "Sponsors 14"
    - listitem:
      - link "Bookmarks 7"
- text: light_high_contrast
- navigation "With icons and counters":
  - list:
    - listitem:
      - link "Stars 10"
    - listitem:
      - link "Sponsors 14"
    - listitem:
      - link "Bookmarks 7"
- text: dark
- navigation "With icons and counters":
  - list:
    - listitem:
      - link "Stars 10"
    - listitem:
      - link "Sponsors 14"
    - listitem:
      - link "Bookmarks 7"
- text: dark_dimmed
- navigation "With icons and counters":
  - list:
    - listitem:
      - link "Stars 10"
    - listitem:
      - link "Sponsors 14"
    - listitem:
      - link "Bookmarks 7"
- text: dark_high_contrast
- navigation "With icons and counters":
  - list:
    - listitem:
      - link "Stars 10"
    - listitem:
      - link "Sponsors 14"
    - listitem:
      - link "Bookmarks 7"
- text: dark_colorblind