- img "Security - secure vault"
- heading "Millions of teams trust GitHub to keep their work safe" [level=2]
- text: light
- img "Security - secure vault"
- heading "Millions of teams trust GitHub to keep their work safe" [level=2]
- text: light_colorblind
- img "Security - secure vault"
- heading "Millions of teams trust GitHub to keep their work safe" [level=2]
- text: light_high_contrast
- img "Security - secure vault"
- heading "Millions of teams trust GitHub to keep their work safe" [level=2]
- text: dark
- img "Security - secure vault"
- heading "Millions of teams trust GitHub to keep their work safe" [level=2]
- text: dark_dimmed
- img "Security - secure vault"
- heading "Millions of teams trust GitHub to keep their work safe" [level=2]
- text: dark_high_contrast
- img "Security - secure vault"
- heading "Millions of teams trust GitHub to keep their work safe" [level=2]
- text: dark_colorblind