- navigation "Repository settings":
  - heading "Repository settings" [level=2]
  - list:
    - listitem:
      - link "General"
    - listitem:
      - link "Settings"
    - listitem:
      - heading "Access" [level=3]
      - list "Access":
        - listitem:
          - link "hulk_smash Bruce Banner"
        - listitem:
          - link "Collaborators and teams"
        - listitem:
          - button "Moderation options" [expanded]
          - list "Moderation options":
            - listitem:
              - link "Interaction limits"
            - listitem:
              - link "Code review limits"
            - listitem:
              - link "Reported content"
- text: light
- navigation "Repository settings":
  - heading "Repository settings" [level=2]
  - list:
    - listitem:
      - link "General"
    - listitem:
      - link "Settings"
    - listitem:
      - heading "Access" [level=3]
      - list "Access":
        - listitem:
          - link "hulk_smash Bruce Banner"
        - listitem:
          - link "Collaborators and teams"
        - listitem:
          - button "Moderation options" [expanded]
          - list "Moderation options":
            - listitem:
              - link "Interaction limits"
            - listitem:
              - link "Code review limits"
            - listitem:
              - link "Reported content"
- text: light_colorblind
- navigation "Repository settings":
  - heading "Repository settings" [level=2]
  - list:
    - listitem:
      - link "General"
    - listitem:
      - link "Settings"
    - listitem:
      - heading "Access" [level=3]
      - list "Access":
        - listitem:
          - link "hulk_smash Bruce Banner"
        - listitem:
          - link "Collaborators and teams"
        - listitem:
          - button "Moderation options" [expanded]
          - list "Moderation options":
            - listitem:
              - link "Interaction limits"
            - listitem:
              - link "Code review limits"
            - listitem:
              - link "Reported content"
- text: light_high_contrast
- navigation "Repository settings":
  - heading "Repository settings" [level=2]
  - list:
    - listitem:
      - link "General"
    - listitem:
      - link "Settings"
    - listitem:
      - heading "Access" [level=3]
      - list "Access":
        - listitem:
          - link "hulk_smash Bruce Banner"
        - listitem:
          - link "Collaborators and teams"
        - listitem:
          - button "Moderation options" [expanded]
          - list "Moderation options":
            - listitem:
              - link "Interaction limits"
            - listitem:
              - link "Code review limits"
            - listitem:
              - link "Reported content"
- text: dark
- navigation "Repository settings":
  - heading "Repository settings" [level=2]
  - list:
    - listitem:
      - link "General"
    - listitem:
      - link "Settings"
    - listitem:
      - heading "Access" [level=3]
      - list "Access":
        - listitem:
          - link "hulk_smash Bruce Banner"
        - listitem:
          - link "Collaborators and teams"
        - listitem:
          - button "Moderation options" [expanded]
          - list "Moderation options":
            - listitem:
              - link "Interaction limits"
            - listitem:
              - link "Code review limits"
            - listitem:
              - link "Reported content"
- text: dark_dimmed
- navigation "Repository settings":
  - heading "Repository settings" [level=2]
  - list:
    - listitem:
      - link "General"
    - listitem:
      - link "Settings"
    - listitem:
      - heading "Access" [level=3]
      - list "Access":
        - listitem:
          - link "hulk_smash Bruce Banner"
        - listitem:
          - link "Collaborators and teams"
        - listitem:
          - button "Moderation options" [expanded]
          - list "Moderation options":
            - listitem:
              - link "Interaction limits"
            - listitem:
              - link "Code review limits"
            - listitem:
              - link "Reported content"
- text: dark_high_contrast
- navigation "Repository settings":
  - heading "Repository settings" [level=2]
  - list:
    - listitem:
      - link "General"
    - listitem:
      - link "Settings"
    - listitem:
      - heading "Access" [level=3]
      - list "Access":
        - listitem:
          - link "hulk_smash Bruce Banner"
        - listitem:
          - link "Collaborators and teams"
        - listitem:
          - button "Moderation options" [expanded]
          - list "Moderation options":
            - listitem:
              - link "Interaction limits"
            - listitem:
              - link "Code review limits"
            - listitem:
              - link "Reported content"
- text: dark_colorblind