- button [pressed]
- text: light
- button [pressed]
- text: light_colorblind
- button [pressed]
- text: light_high_contrast
- button [pressed]
- text: dark
- button [pressed]
- text: dark_dimmed
- button [pressed]
- text: dark_high_contrast
- button [pressed]
- text: dark_colorblind