- checkbox "Jean-Luc Picard Jean-Luc Picard Jean-Luc Picard Jean-Luc Picard Jean-Luc Picard Jean-Luc Picard Jean-Luc Picard": "1"
- text: Jean-Luc Picard With a caption light
- checkbox: "1"
- text: Jean-Luc Picard With a caption light_colorblind
- checkbox: "1"
- text: Jean-Luc Picard With a caption light_high_contrast
- checkbox: "1"
- text: Jean-Luc Picard With a caption dark
- checkbox: "1"
- text: Jean-Luc Picard With a caption dark_dimmed
- checkbox: "1"
- text: Jean-Luc Picard With a caption dark_high_contrast
- checkbox: "1"
- text: Jean-Luc Picard With a caption dark_colorblind