- heading "Heading" [level=2]
- text: light
- heading "Heading" [level=2]
- text: light_colorblind
- heading "Heading" [level=2]
- text: light_high_contrast
- heading "Heading" [level=2]
- text: dark
- heading "Heading" [level=2]
- text: dark_dimmed
- heading "Heading" [level=2]
- text: dark_high_contrast
- heading "Heading" [level=2]
- text: dark_colorblind