- navigation "Breadcrumb":
  - list:
    - listitem:
      - link "Breadcrumb Item 1"
    - listitem:
      - link "Breadcrumb Item 2 with a really long, long, long name"
    - listitem:
      - link "Breadcrumb Item 3 with an extremely long, long, long name"
- text: light
- navigation "Breadcrumb":
  - list:
    - listitem:
      - link "Breadcrumb Item 1"
    - listitem:
      - link "Breadcrumb Item 2 with a really long, long, long name"
    - listitem:
      - link "Breadcrumb Item 3 with an extremely long, long, long name"
- text: light_colorblind
- navigation "Breadcrumb":
  - list:
    - listitem:
      - link "Breadcrumb Item 1"
    - listitem:
      - link "Breadcrumb Item 2 with a really long, long, long name"
    - listitem:
      - link "Breadcrumb Item 3 with an extremely long, long, long name"
- text: light_high_contrast
- navigation "Breadcrumb":
  - list:
    - listitem:
      - link "Breadcrumb Item 1"
    - listitem:
      - link "Breadcrumb Item 2 with a really long, long, long name"
    - listitem:
      - link "Breadcrumb Item 3 with an extremely long, long, long name"
- text: dark
- navigation "Breadcrumb":
  - list:
    - listitem:
      - link "Breadcrumb Item 1"
    - listitem:
      - link "Breadcrumb Item 2 with a really long, long, long name"
    - listitem:
      - link "Breadcrumb Item 3 with an extremely long, long, long name"
- text: dark_dimmed
- navigation "Breadcrumb":
  - list:
    - listitem:
      - link "Breadcrumb Item 1"
    - listitem:
      - link "Breadcrumb Item 2 with a really long, long, long name"
    - listitem:
      - link "Breadcrumb Item 3 with an extremely long, long, long name"
- text: dark_high_contrast
- navigation "Breadcrumb":
  - list:
    - listitem:
      - link "Breadcrumb Item 1"
    - listitem:
      - link "Breadcrumb Item 2 with a really long, long, long name"
    - listitem:
      - link "Breadcrumb Item 3 with an extremely long, long, long name"
- text: dark_colorblind