- tablist "Test navigation":
  - tab "Tab 1 5" [selected]
  - tab "Tab 2 10"
  - tab "Tab 3 15"
- tabpanel "Tab 1 5": Panel 1
- text: light
- tablist "Test navigation":
  - tab "Tab 1 5" [selected]
  - tab "Tab 2 10"
  - tab "Tab 3 15"
- tabpanel "Tab 1 5": Panel 1
- text: light_colorblind
- tablist "Test navigation":
  - tab "Tab 1 5" [selected]
  - tab "Tab 2 10"
  - tab "Tab 3 15"
- tabpanel "Tab 1 5": Panel 1
- text: light_high_contrast
- tablist "Test navigation":
  - tab "Tab 1 5" [selected]
  - tab "Tab 2 10"
  - tab "Tab 3 15"
- tabpanel "Tab 1 5": Panel 1
- text: dark
- tablist "Test navigation":
  - tab "Tab 1 5" [selected]
  - tab "Tab 2 10"
  - tab "Tab 3 15"
- tabpanel "Tab 1 5": Panel 1
- text: dark_dimmed
- tablist "Test navigation":
  - tab "Tab 1 5" [selected]
  - tab "Tab 2 10"
  - tab "Tab 3 15"
- tabpanel "Tab 1 5": Panel 1
- text: dark_high_contrast
- tablist "Test navigation":
  - tab "Tab 1 5" [selected]
  - tab "Tab 2 10"
  - tab "Tab 3 15"
- tabpanel "Tab 1 5": Panel 1
- text: dark_colorblind