- group "I would go into battle with:":
  - text: "I would go into battle with: With a caption"
  - checkbox "Jean-Luc Picard Jean-Luc Picard Jean-Luc Picard Jean-Luc Picard Jean-Luc Picard Jean-Luc Picard Jean-Luc Picard": picard1
  - text: Jean-Luc Picard
  - checkbox "Hikaru Sulu Hikaru Sulu Hikaru Sulu Hikaru Sulu Hikaru Sulu Hikaru Sulu Hikaru Sulu": sulu1
  - text: Hikaru Sulu
  - checkbox "Kathryn Janeway Kathryn Janeway Kathryn Janeway Kathryn Janeway Kathryn Janeway Kathryn Janeway Kathryn Janeway": janeway1
  - text: Kathryn Janeway
  - checkbox "Benjamin Sisko Benjamin Sisko Benjamin Sisko Benjamin Sisko Benjamin Sisko Benjamin Sisko Benjamin Sisko": sisko1
  - text: Benjamin Sisko
- text: light
- group "I would go into battle with:":
  - text: "I would go into battle with: With a caption"
  - checkbox: picard1
  - text: Jean-Luc Picard
  - checkbox: sulu1
  - text: Hikaru Sulu
  - checkbox: janeway1
  - text: Kathryn Janeway
  - checkbox: sisko1
  - text: Benjamin Sisko
- text: light_colorblind
- group "I would go into battle with:":
  - text: "I would go into battle with: With a caption"
  - checkbox: picard1
  - text: Jean-Luc Picard
  - checkbox: sulu1
  - text: Hikaru Sulu
  - checkbox: janeway1
  - text: Kathryn Janeway
  - checkbox: sisko1
  - text: Benjamin Sisko
- text: light_high_contrast
- group "I would go into battle with:":
  - text: "I would go into battle with: With a caption"
  - checkbox: picard1
  - text: Jean-Luc Picard
  - checkbox: sulu1
  - text: Hikaru Sulu
  - checkbox: janeway1
  - text: Kathryn Janeway
  - checkbox: sisko1
  - text: Benjamin Sisko
- text: dark
- group "I would go into battle with:":
  - text: "I would go into battle with: With a caption"
  - checkbox: picard1
  - text: Jean-Luc Picard
  - checkbox: sulu1
  - text: Hikaru Sulu
  - checkbox: janeway1
  - text: Kathryn Janeway
  - checkbox: sisko1
  - text: Benjamin Sisko
- text: dark_dimmed
- group "I would go into battle with:":
  - text: "I would go into battle with: With a caption"
  - checkbox: picard1
  - text: Jean-Luc Picard
  - checkbox: sulu1
  - text: Hikaru Sulu
  - checkbox: janeway1
  - text: Kathryn Janeway
  - checkbox: sisko1
  - text: Benjamin Sisko
- text: dark_high_contrast
- group "I would go into battle with:":
  - text: "I would go into battle with: With a caption"
  - checkbox: picard1
  - text: Jean-Luc Picard
  - checkbox: sulu1
  - text: Hikaru Sulu
  - checkbox: janeway1
  - text: Kathryn Janeway
  - checkbox: sisko1
  - text: Benjamin Sisko
- text: dark_colorblind