- radiogroup "How did you hear about us?":
  - text: How did you hear about us? We love our listeners
  - radio "Online advertisement Online advertisement Online advertisement Online advertisement Online advertisement Online advertisement Online advertisement": online
  - text: Online advertisement Facebook maybe?
  - radio "Radio advertisement Radio advertisement Radio advertisement Radio advertisement Radio advertisement Radio advertisement Radio advertisement": radio
  - text: Radio advertisement We love us some NPR
  - radio "From a friend From a friend From a friend From a friend From a friend From a friend From a friend": friend
  - text: From a friend Wow, what a good person
- text: light
- radiogroup "How did you hear about us?":
  - text: How did you hear about us? We love our listeners
  - radio: online
  - text: Online advertisement Facebook maybe?
  - radio: radio
  - text: Radio advertisement We love us some NPR
  - radio: friend
  - text: From a friend Wow, what a good person
- text: light_colorblind
- radiogroup "How did you hear about us?":
  - text: How did you hear about us? We love our listeners
  - radio: online
  - text: Online advertisement Facebook maybe?
  - radio: radio
  - text: Radio advertisement We love us some NPR
  - radio: friend
  - text: From a friend Wow, what a good person
- text: light_high_contrast
- radiogroup "How did you hear about us?":
  - text: How did you hear about us? We love our listeners
  - radio: online
  - text: Online advertisement Facebook maybe?
  - radio: radio
  - text: Radio advertisement We love us some NPR
  - radio: friend
  - text: From a friend Wow, what a good person
- text: dark
- radiogroup "How did you hear about us?":
  - text: How did you hear about us? We love our listeners
  - radio: online
  - text: Online advertisement Facebook maybe?
  - radio: radio
  - text: Radio advertisement We love us some NPR
  - radio: friend
  - text: From a friend Wow, what a good person
- text: dark_dimmed
- radiogroup "How did you hear about us?":
  - text: How did you hear about us? We love our listeners
  - radio: online
  - text: Online advertisement Facebook maybe?
  - radio: radio
  - text: Radio advertisement We love us some NPR
  - radio: friend
  - text: From a friend Wow, what a good person
- text: dark_high_contrast
- radiogroup "How did you hear about us?":
  - text: How did you hear about us? We love our listeners
  - radio: online
  - text: Online advertisement Facebook maybe?
  - radio: radio
  - text: Radio advertisement We love us some NPR
  - radio: friend
  - text: From a friend Wow, what a good person
- text: dark_colorblind