- text: Tell me about yourself
- textbox "Tell me about yourself Tell me about yourself Tell me about yourself Tell me about yourself Tell me about yourself Tell me about yourself Tell me about yourself" [disabled]
- text: light Tell me about yourself
- textbox [disabled]
- text: light_colorblind Tell me about yourself
- textbox [disabled]
- text: light_high_contrast Tell me about yourself
- textbox [disabled]
- text: dark Tell me about yourself
- textbox [disabled]
- text: dark_dimmed Tell me about yourself
- textbox [disabled]
- text: dark_high_contrast Tell me about yourself
- textbox [disabled]
- text: dark_colorblind