- text: My text field
- textbox "My text field My text field My text field My text field My text field My text field My text field"
- text: light My text field
- textbox
- text: light_colorblind My text field
- textbox
- text: light_high_contrast My text field
- textbox
- text: dark My text field
- textbox
- text: dark_dimmed My text field
- textbox
- text: dark_high_contrast My text field
- textbox
- text: dark_colorblind