- navigation "Default":
  - list:
    - listitem:
      - link "Tab 1"
    - listitem:
      - link "Tab 2"
    - listitem:
      - link "Tab 3"
- text: light
- navigation "Default":
  - list:
    - listitem:
      - link "Tab 1"
    - listitem:
      - link "Tab 2"
    - listitem:
      - link "Tab 3"
- text: light_colorblind
- navigation "Default":
  - list:
    - listitem:
      - link "Tab 1"
    - listitem:
      - link "Tab 2"
    - listitem:
      - link "Tab 3"
- text: light_high_contrast
- navigation "Default":
  - list:
    - listitem:
      - link "Tab 1"
    - listitem:
      - link "Tab 2"
    - listitem:
      - link "Tab 3"
- text: dark
- navigation "Default":
  - list:
    - listitem:
      - link "Tab 1"
    - listitem:
      - link "Tab 2"
    - listitem:
      - link "Tab 3"
- text: dark_dimmed
- navigation "Default":
  - list:
    - listitem:
      - link "Tab 1"
    - listitem:
      - link "Tab 2"
    - listitem:
      - link "Tab 3"
- text: dark_high_contrast
- navigation "Default":
  - list:
    - listitem:
      - link "Tab 1"
    - listitem:
      - link "Tab 2"
    - listitem:
      - link "Tab 3"
- text: dark_colorblind