- navigation "Workflow results":
  - heading "Workflows" [level=3]
  - list "Workflows":
    - listitem:
      - link "Build and Test"
      - 'button "Build and test: re-run workflow"'
    - listitem:
      - link "Publish"
      - 'button "Publish: re-run workflow"'
- text: light
- navigation "Workflow results":
  - heading "Workflows" [level=3]
  - list "Workflows":
    - listitem:
      - link "Build and Test"
      - 'button "Build and test: re-run workflow"'
    - listitem:
      - link "Publish"
      - 'button "Publish: re-run workflow"'
- text: light_colorblind
- navigation "Workflow results":
  - heading "Workflows" [level=3]
  - list "Workflows":
    - listitem:
      - link "Build and Test"
      - 'button "Build and test: re-run workflow"'
    - listitem:
      - link "Publish"
      - 'button "Publish: re-run workflow"'
- text: light_high_contrast
- navigation "Workflow results":
  - heading "Workflows" [level=3]
  - list "Workflows":
    - listitem:
      - link "Build and Test"
      - 'button "Build and test: re-run workflow"'
    - listitem:
      - link "Publish"
      - 'button "Publish: re-run workflow"'
- text: dark
- navigation "Workflow results":
  - heading "Workflows" [level=3]
  - list "Workflows":
    - listitem:
      - link "Build and Test"
      - 'button "Build and test: re-run workflow"'
    - listitem:
      - link "Publish"
      - 'button "Publish: re-run workflow"'
- text: dark_dimmed
- navigation "Workflow results":
  - heading "Workflows" [level=3]
  - list "Workflows":
    - listitem:
      - link "Build and Test"
      - 'button "Build and test: re-run workflow"'
    - listitem:
      - link "Publish"
      - 'button "Publish: re-run workflow"'
- text: dark_high_contrast
- navigation "Workflow results":
  - heading "Workflows" [level=3]
  - list "Workflows":
    - listitem:
      - link "Build and Test"
      - 'button "Build and test: re-run workflow"'
    - listitem:
      - link "Publish"
      - 'button "Publish: re-run workflow"'
- text: dark_colorblind