#!/usr/bin/env bash

npm install -g @axe-core/cli

# Find all component markdown files containing examples
files=($(grep -r -l "Examples" docs/content/components))

# Exclude known violations
declare -a needs_to_be_fixed=(
  autocomplete 
  autocompleteitem
  dropdown
  dropdownmenu
  imagecrop
  markdown
  navigationtab
)

echo "############################################################"
echo "WARNING"
echo "The following components will be excluded from this automated accessibility check."
echo "They contain known violations and should be addressed:"
printf '%s\n' "${needs_to_be_fixed[@]}"
echo "############################################################"

# Generate doc urls 
declare -a doc_urls

for i in "${!files[@]}"; 
do
  filename=$(basename -- "${files[$i]}")
  component="${filename%.*}"
  if [[ " ${needs_to_be_fixed[@]} " =~ " ${component} " ]]
  then
      continue
  else
      doc_urls+=("localhost:5400/components/${component}")
fi
done

# Run axe on generated URLs
printf -v joined '%s, ' "${doc_urls[@]}"
axe $joined -i .frame-example --save docs-example-accessibility.json --disable color-contrast,landmark-unique --exit
