#! /bin/bash -e

script/copy-pcss-source-files
npm run build:pcss
npm run build:pcss:stats
bundle exec rake utilities:build
cp app/assets/styles/utilities.css ../css/dist/
echo "Copied utilities.css to ../css/dist"
