#!/bin/bash

export INPUT_TYPE=$1

build_css() {
  # Get a list of all the CSS files in the src directory
  PCSS_FILES=$(find app/components/primer -name '*.pcss' ! -path '*/primer.pcss')
  npx postcss $PCSS_FILES --dir app/components --base app/components --ext css
  # Build main CSS bundle
  npx postcss -o app/assets/styles/primer_view_components.css app/components/primer/primer.pcss

  CSS_FILES=$(find app/components/primer -name '*.css')

  for css_file in $CSS_FILES; do
    cp $css_file app/assets/styles/primer_view_components/
  done

  # Export CSS selectors as json
  script/export-css-selectors
}

# Function to build the assets
build_js() {
  # Build the assets
  npx tsc
  npx rollup -c
}

if [ "$INPUT_TYPE" = "css" ]; then
  echo "Building CSS assets..."
  build_css
elif [ "$INPUT_TYPE" = "js" ]; then
  # run build_js
  echo "Building JS assets..."
  build_js
else
  echo "Building all assets..."
  build_js
  build_css
fi
