#!/bin/sh

# Gems
bundle install --path vendor/bundle
npm install

# Set up demo
pushd demo
bundle install --path vendor/bundle
yarn install
popd

# Set up docs
pushd docs
yarn install
popd

exec overmind start
