#!/usr/bin/env bash

if ! command -v overmind &> /dev/null
then
  echo "Please install overmind."
  exit 1
fi

# Gems
bundle config set --local path 'vendor/bundle'
bundle check || bundle install
npm install --ignore-scripts

# Set up demo
pushd demo
bundle config set --local path 'vendor/bundle'
bundle check || bundle install
npm install --ignore-scripts
popd

npm run build:css

while [[ "$#" > 0 ]]; do case $1 in
  -d|--debug) debug="1"; shift;;
esac; done

if [ -n "$debug" ]; then
  # start vite and css processes in the background
  overmind start --daemonize --processes vite,css

  # ensure we cleanup tmp files and overmind
  function cleanup {
    echo "Shutting down..."
    popd
    overmind stop
    rm .overmind.sock
  }

  trap cleanup EXIT

  pushd demo
  bin/rails server -p 4000
else
  exec overmind start "$@"
fi
