#!/usr/bin/env bash

read -p "Bump gem (y/N)? " answer
case ${answer:0:1} in
    y|Y )
        bump_gem=1
    ;;
    * )
        bump_gem=0
    ;;
esac

read -p "Bump NPM (y/N)? " answer
case ${answer:0:1} in
    y|Y )
        bump_npm=1
    ;;
    * )
        bump_npm=0
    ;;
esac

# Create release branch
git checkout -B release

if [[ $bump_gem -eq 1 ]]
then
  script/release-gem

  git add \
    CHANGELOG.md \
    Gemfile.lock \
    demo/Gemfile.lock \
    lib/primer/view_components/version.rb
fi

if [[ $bump_npm -eq 1 ]]
then
  script/release-npm

  git add \
    package.json \
    app/assets/javascripts/
fi

# Commit and push
git commit -m "release"
# git push origin release

echo "####################################################"
echo "Now, open a PR with this branch and merge it to main"
echo "Then, run script/publish on main to release the gem and the NPM package"
echo "Finally, create a GitHub release https://github.com/primer/view_components/releases/new with the changes from CHANGELOG"
echo "####################################################"
