#!/usr/bin/env bash

echo "####################################################"
echo "NPM version:"
echo "####################################################"

read -p "MAJOR: " major
read -p "MINOR: " minor
read -p "PATCH: " patch

# Update package.json version
npm version --no-git-tag-version "$major.$minor.$patch"

# Update lock and assets
yarn
