#!/bin/bash

# Gems
bundle install --path vendor/bundle
npm install

# Set up demo
pushd demo
bundle install --path vendor/bundle
npm install
popd

# Initial build of docs content
bundle exec rake docs:build
