#!/bin/bash

# Gems
mkdir -p vendor/bundle
chmod 0700 vendor/bundle
bundle config set --local path 'vendor/bundle'
bundle install
npm install

# Set up demo
pushd demo
mkdir -p vendor/bundle
chmod 0700 vendor/bundle
bundle config set --local path 'vendor/bundle'
bundle install
npm install
popd

# Initial build of docs content
bundle exec rake docs:build
