#!/bin/bash

# Gems
bundle install --path vendor/bundle
yarn install

# Set up lookbook
pushd demo
bundle install --path vendor/bundle
yarn install
yarn build:css
popd

# Set up docs
pushd docs
yarn install
popd

# Initial build of docs content
bundle exec rake docs:build
