#!/bin/sh

if command -v overmind &> /dev/null
then
  exec overmind start
else
  cd demo

  bin/rails view_component_storybook:write_stories_json
  STORYBOOK=true bin/rails s -p 4000 &
  STORYBOOK=true bin/yarn storybook -p 5000
fi
