#!/bin/sh

if command -v overmind &> /dev/null
then
  exec overmind start
else
  cd test/demo

  bin/rails view_component_storybook:write_stories_json
  bin/rails s -p 4000 &
  bin/yarn storybook -p 5000
fi
