#!/usr/bin/env ruby
# frozen_string_literal: true

require "thor"

# Update `@primer/css` npm package across project
#
# Usage:
#
# script/upgrade-primer-css
#   for latest version
# script/upgrade-primer-css 17.0.0
#   for named version
class UpgradePrimerCSSCLI < Thor::Group
  include Thor::Actions

  def upgrade_root
    run(install_command)
  end

  def upgrade_demo
    run("cd demo && #{install_command}")
  end

  private

  def version
    args[0] || "latest"
  end

  def install_command
    "npm install @primer/css@#{version}"
  end
end

UpgradePrimerCSSCLI.start(ARGV)
