#!/usr/bin/env ruby
# frozen_string_literal: true

require "thor"
require_relative "../lib/primer/view_components/version"

# Versions primer_view_components gem based on the package.json file.
#
# Usage:
#
# script/version
class ReleaseCLI < Thor::Group
  include Thor::Actions

  def self.exit_on_failure?
    false
  end

  def update_ruby_version
    major, minor, patch = new_version.split(".")

    gsub_file("lib/primer/view_components/version.rb", /MAJOR = [0-9]+/, "MAJOR = #{major}")
    gsub_file("lib/primer/view_components/version.rb", /MINOR = [0-9]+/, "MINOR = #{minor}")
    gsub_file("lib/primer/view_components/version.rb", /PATCH = [0-9]+/, "PATCH = #{patch}")
  end

  def update_gemfiles
    run("bundle")
    run("cd demo && bundle")
  end

  def update_package_lock
    run("npm i --package-lock-only")
  end

  private

  def current_version
    Primer::ViewComponents::VERSION::STRING
  end

  def new_version
    @new_version ||= run("jq '.version' --raw-output ./package.json", capture: true).strip
  end
end

ReleaseCLI.start(ARGV)
