- text: My text field
- textbox "My text field My text field My text field My text field My text field My text field My text field" [disabled]
- text: light My text field
- textbox [disabled]
- text: light_colorblind My text field
- textbox [disabled]
- text: light_high_contrast My text field
- textbox [disabled]
- text: dark My text field
- textbox [disabled]
- text: dark_dimmed My text field
- textbox [disabled]
- text: dark_high_contrast My text field
- textbox [disabled]
- text: dark_colorblind