- text: This is a dismissible flash message!
- button "Dismiss alert"
- text: light This is a dismissible flash message!
- button "Dismiss alert"
- text: light_colorblind This is a dismissible flash message!
- button "Dismiss alert"
- text: light_high_contrast This is a dismissible flash message!
- button "Dismiss alert"
- text: dark This is a dismissible flash message!
- button "Dismiss alert"
- text: dark_dimmed This is a dismissible flash message!
- button "Dismiss alert"
- text: dark_high_contrast This is a dismissible flash message!
- button "Dismiss alert"
- text: dark_colorblind