- 'radiogroup "Question: what kind of bear is best?"':
  - text: "Question: what kind of bear is best? With a caption"
  - radio "Bears Bears Bears Bears Bears Bears Bears": bears1
  - text: Bears
  - radio "Beets Beets Beets Beets Beets Beets Beets": beets1
  - text: Beets
  - radio "Battlestar Galactica Battlestar Galactica Battlestar Galactica Battlestar Galactica Battlestar Galactica Battlestar Galactica Battlestar Galactica": bsg1
  - text: Battlestar Galactica
- text: light
- 'radiogroup "Question: what kind of bear is best?"':
  - text: "Question: what kind of bear is best? With a caption"
  - radio: bears1
  - text: Bears
  - radio: beets1
  - text: Beets
  - radio: bsg1
  - text: Battlestar Galactica
- text: light_colorblind
- 'radiogroup "Question: what kind of bear is best?"':
  - text: "Question: what kind of bear is best? With a caption"
  - radio: bears1
  - text: Bears
  - radio: beets1
  - text: Beets
  - radio: bsg1
  - text: Battlestar Galactica
- text: light_high_contrast
- 'radiogroup "Question: what kind of bear is best?"':
  - text: "Question: what kind of bear is best? With a caption"
  - radio: bears1
  - text: Bears
  - radio: beets1
  - text: Beets
  - radio: bsg1
  - text: Battlestar Galactica
- text: dark
- 'radiogroup "Question: what kind of bear is best?"':
  - text: "Question: what kind of bear is best? With a caption"
  - radio: bears1
  - text: Bears
  - radio: beets1
  - text: Beets
  - radio: bsg1
  - text: Battlestar Galactica
- text: dark_dimmed
- 'radiogroup "Question: what kind of bear is best?"':
  - text: "Question: what kind of bear is best? With a caption"
  - radio: bears1
  - text: Bears
  - radio: beets1
  - text: Beets
  - radio: bsg1
  - text: Battlestar Galactica
- text: dark_high_contrast
- 'radiogroup "Question: what kind of bear is best?"':
  - text: "Question: what kind of bear is best? With a caption"
  - radio: bears1
  - text: Bears
  - radio: beets1
  - text: Beets
  - radio: bsg1
  - text: Battlestar Galactica
- text: dark_colorblind