# frozen_string_literal: true

source "https://rubygems.org"

rails_version = (ENV["RAILS_VERSION"] || "7.0.3").to_s

gem "rake", "~> 13.0"
gem "rack-cors"
gem "sprockets"
gem "sprockets-rails"
# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
if rails_version != "main"
  gem "actionview", rails_version
  gem "activemodel", rails_version
  gem "activesupport", rails_version
  gem "railties", rails_version
else
  git "https://github.com/rails/rails", ref: "main" do
    # rubocop:disable Bundler/DuplicatedGem
    gem "actionview"
    gem "activemodel"
    gem "activerecord"
    gem "activesupport"
    gem "railties"
    # rubocop:enable Bundler/DuplicatedGem
  end
end

eval_gemfile "gemfiles/kuby.gemfile"

# Use Puma as the app server
gem "puma", "~> 5.6.4"

# Reduces boot times through caching; required in config/boot.rb
gem "bootsnap", ">= 1.4.2", require: false

gem "primer_view_components", path: "../"
gem "view_component_storybook", "~> 0.8.0"

group :development do
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem "spring"
  gem "spring-watcher-listen", "~> 2.0.0"
  gem "hotwire-livereload", "~> 1.1"
  # Use JavaScript with ESM import maps [https://github.com/rails/importmap-rails]
  gem "importmap-rails"

  # Hotwire's SPA-like page accelerator [https://turbo.hotwired.dev]
  gem "turbo-rails"

  # Hotwire's modest JavaScript framework [https://stimulus.hotwired.dev]
  gem "stimulus-rails"
end
