# frozen_string_literal: true

source "https://rubygems.org"

rails_version = (ENV["RAILS_VERSION"] || "6.1.1").to_s

gem "rake", "~> 12.0"
gem "rack-cors"
# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
if ENV["RAILS_VERSION"] != "main"
  gem "actionview", rails_version
  gem "activemodel", rails_version
  gem "activesupport", rails_version
  gem "railties", rails_version
else
  git "https://github.com/rails/rails.git", ref: "main" do
    gem "actionview"
    gem "activemodel"
    gem "activesupport"
    gem "railties"
  end
end

# Use Puma as the app server
gem "puma", "~> 4.3.6"

# Reduces boot times through caching; required in config/boot.rb
gem "bootsnap", ">= 1.4.2", require: false

gem "primer_view_components", path: "../"
gem "view_component_storybook", "~> 0.8.0"

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem "sprockets"
  gem "sprockets-rails"
end

group :development do
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem "spring"
  gem "spring-watcher-listen", "~> 2.0.0"
end
