# frozen_string_literal: true

# Add your own tasks in files placed in lib/tasks ending in .rake,
# for example lib/tasks/capistrano.rake, and they will automatically be available to Rake.

require_relative "config/application"

Rails.application.load_tasks

Rake::Task["assets:precompile"].clear
namespace :assets do
  task "precompile" do
    Rake::Task["view_component_storybook:write_stories_json"].invoke
  end
end
