- img "Circled container icon"
- text: light
- img "Circled container icon"
- text: light_colorblind
- img "Circled container icon"
- text: light_high_contrast
- img "Circled container icon"
- text: dark
- img "Circled container icon"
- text: dark_dimmed
- img "Circled container icon"
- text: dark_high_contrast
- img "Circled container icon"
- text: dark_colorblind