- text: Actions Content
- tablist "Test navigation":
  - tab "Tab 1" [selected]
  - tab "Tab 2"
  - tab "Tab 3"
- tabpanel "Tab 1": Panel 1
- text: light Actions Content
- tablist "Test navigation":
  - tab "Tab 1" [selected]
  - tab "Tab 2"
  - tab "Tab 3"
- tabpanel "Tab 1": Panel 1
- text: light_colorblind Actions Content
- tablist "Test navigation":
  - tab "Tab 1" [selected]
  - tab "Tab 2"
  - tab "Tab 3"
- tabpanel "Tab 1": Panel 1
- text: light_high_contrast Actions Content
- tablist "Test navigation":
  - tab "Tab 1" [selected]
  - tab "Tab 2"
  - tab "Tab 3"
- tabpanel "Tab 1": Panel 1
- text: dark Actions Content
- tablist "Test navigation":
  - tab "Tab 1" [selected]
  - tab "Tab 2"
  - tab "Tab 3"
- tabpanel "Tab 1": Panel 1
- text: dark_dimmed Actions Content
- tablist "Test navigation":
  - tab "Tab 1" [selected]
  - tab "Tab 2"
  - tab "Tab 3"
- tabpanel "Tab 1": Panel 1
- text: dark_high_contrast Actions Content
- tablist "Test navigation":
  - tab "Tab 1" [selected]
  - tab "Tab 2"
  - tab "Tab 3"
- tabpanel "Tab 1": Panel 1
- text: dark_colorblind