- 'button "Menu: Quote reply"'
- text: light
- 'button "Menu: Quote reply"'
- text: light_colorblind
- 'button "Menu: Quote reply"'
- text: light_high_contrast
- 'button "Menu: Quote reply"'
- text: dark
- 'button "Menu: Quote reply"'
- text: dark_dimmed
- 'button "Menu: Quote reply"'
- text: dark_high_contrast
- 'button "Menu: Quote reply"'
- text: dark_colorblind