- paragraph: This is a banner with an action!
- button "Take action"
- text: light
- paragraph: This is a banner with an action!
- button "Take action"
- text: light_colorblind
- paragraph: This is a banner with an action!
- button "Take action"
- text: light_high_contrast
- paragraph: This is a banner with an action!
- button "Take action"
- text: dark
- paragraph: This is a banner with an action!
- button "Take action"
- text: dark_dimmed
- paragraph: This is a banner with an action!
- button "Take action"
- text: dark_high_contrast
- paragraph: This is a banner with an action!
- button "Take action"
- text: dark_colorblind