- link "Button"
- text: light
- link "Button"
- text: light_colorblind
- link "Button"
- text: light_high_contrast
- link "Button"
- text: dark
- link "Button"
- text: dark_dimmed
- link "Button"
- text: dark_high_contrast
- link "Button"
- text: dark_colorblind