- paragraph: This is a dismissable banner.
- button "Dismiss"
- text: light
- paragraph: This is a dismissable banner.
- button "Dismiss"
- text: light_colorblind
- paragraph: This is a dismissable banner.
- button "Dismiss"
- text: light_high_contrast
- paragraph: This is a dismissable banner.
- button "Dismiss"
- text: dark
- paragraph: This is a dismissable banner.
- button "Dismiss"
- text: dark_dimmed
- paragraph: This is a dismissable banner.
- button "Dismiss"
- text: dark_high_contrast
- paragraph: This is a dismissable banner.
- button "Dismiss"
- text: dark_colorblind