name: Cameron

on:
  pull_request:
    branches:
      - '*'

jobs:
  get-access-token:
    name: Get access token
    uses: primer/.github/.github/workflows/get_access_token.yml@main
    secrets: inherit
  list:
    runs-on: ubuntu-latest
    needs: get-access-token
    steps:
      - name: List codespaces
        run: gh codespace list
        env:
          # GH_TOKEN: ${{ github.token }}
          GH_TOKEN: ${{ needs.get-access-token.outputs.access-token }}
