name: Cameron

on:
  pull_request:
    branches:
      - '*'

jobs:
  cameron:
    runs-on: ubuntu-latest
    uses: primer/.github/.github/workflows/get_access_token.yml@main
  list:
    runs-on: ubuntu-latest
    steps:
      - name: List codespaces
        run: gh codespace list
        env:
          # GH_TOKEN: ${{ github.token }}
          GH_TOKEN: ${{ jobs.cameron.outputs.access-token }}
