name: Cameron

on:
  pull_request:
    branches:
      - '*'

jobs:
  get-access-token:
    name: Get access token
    uses: primer/.github/.github/workflows/get_access_token.yml@main
    secrets: inherit
  list:
    runs-on: ubuntu-latest
    needs: get-access-token
    steps:
      - name: Decrypt access token
        id: decrypt-access-token
        run: echo "access-token=$(echo '${{ needs.get-access-token.outputs.access-token }}' | openssl enc -a -d -aes256 -pbkdf2 -k '${{ secrets.PRIMER_APP_PRIVATE_KEY_SHARED }}')" >> "$GITHUB_OUTPUT"
      - name: List codespaces
        run: gh codespace list
        env:
          GH_TOKEN: ${{ steps.decrypt-access-token.outputs.access-token }}
