name: Cameron

on:
  pull_request:
    branches:
      - '*'

jobs:
  cameron:
    runs-on: ubuntu-latest
    steps:
      - id: get-access-token
        uses: primer/.github/.github/workflows/get_access_token.yml@main

      - name: List codespaces
        run: gh codespace list
        env:
          # GH_TOKEN: ${{ github.token }}
          GH_TOKEN: ${{ steps.get-access-token.outputs.access-token }}
