name: Docs Production
on:
  push:
    branches:
      - 'main'

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout default branch
        uses: actions/checkout@v2
        with:
          version: 14

      - name: Setup Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.7.x

      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: 14
          cache: 'yarn'
          cache-dependency-path: |
            yarn.lock
            docs/yarn.lock

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: gems-deploy-preview-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: yarn && cd docs && yarn && cd ..

      - name: Generate static files
        run: |
          gem install bundler:2.2.9
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
          bundle exec rake utilities:build
          bundle exec rake docs:build
          bundle exec rake static:dump

      - name: Build
        run: yarn build:docs

      - name: Archive build output
        run: 'tar --dereference --directory docs/public -cvf artifact.tar .'

      - name: Upload artifact
        uses: actions/upload-artifact@main
        with:
          name: github-pages
          path: artifact.tar

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: paper-spa/deploy-pages@main
        with:
          preview: false
