name: Kuby Build

on:
  push:
    branches:
      - main
      - azure

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Setup Ruby
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 3.0.x
    - uses: actions/cache@v2
      with:
        path: vendor/bundle
        key: gems-build-kuby-main-ruby-3.0.x-${{ hashFiles('demo/gemfiles/kuby.gemfile.lock') }}
    - name: Build and push
      env: # Or as an environment variable
        RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
        AZURE_ACR_PASSWORD: ${{ secrets.AZURE_ACR_PASSWORD }}
        AZURE_SPN_CLIENT_SECRET: ${{ secrets.AZURE_SPN_CLIENT_SECRET }}
      run: |
        gem install bundler -v '~> 2.3'
        bundle config path vendor/bundle
        bundle install --jobs 4 --retry 3 --gemfile demo/gemfiles/kuby.gemfile
        bin/kuby -e production build
        bin/kuby -e production push
