name: Lock Release Pull Request

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Lock or unlock the release?'
        required: true
        type: choice
        options:
          - lock
          - unlock

jobs:
  lock:
    runs-on: ubuntu-latest
    steps:
      - name: Get App Token
        uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.PRIMER_APP_ID_SHARED }}
          owner: primer
          repositories: view_components
          private-key: ${{ secrets.PRIMER_APP_PRIVATE_KEY_SHARED }}
      - uses: octokit/request-action@v2.x
        with:
          route: PUT /repos/primer/view_components/rulesets/${{ vars.RELEASE_CONDUCTOR_RULE_ID }}
          enforcement: active
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
