name: Release
on:
  push:
  release:
    types: [published]

permissions: {}

jobs:
  publish-main:
    if: ${{ github.event_name == 'release' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write # Required for OIDC
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          persist-credentials: false
      - name: Setup Ruby
        uses: ruby/setup-ruby@6aaa311d81eba98ae12eaffbcb63296ace0efcde # v1
        with:
          ruby-version: "3.4"
          bundler-cache: true
      - uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5
        with:
          node-version: 20
          cache: "npm"
      - name: Create .gem credentials
        run: |
          mkdir -p $HOME/.gem
          cat << EOF > $HOME/.gem/credentials
          ---
          :rubygems_api_key: ${RUBYGEMS_TOKEN}
          EOF
          chmod 0600 $HOME/.gem/credentials
        env:
          RUBYGEMS_TOKEN: ${{ secrets.RUBYGEMS_TOKEN_SHARED }}
      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
        with:
          node-version: 24
          registry-url: 'https://registry.npmjs.org'
      - name: NPM install
        run: |
          npm ci
      - name: Publish Gem
        run: bundle exec rake release
      - name: Publish NPM
        run: npm publish --access public

  release-main:
    name: Main
    if: ${{ github.repository == 'opf/primer_view_components' && github.ref_name == 'main' && github.event_name == 'push' }}

    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          # This makes Actions fetch all Git history so that Changesets can generate changelogs with the correct commits
          fetch-depth: 0
          persist-credentials: false

      - name: Set up Node.js
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
        with:
          node-version: 24
          cache: "npm"

      - name: Setup Ruby
        uses: ruby/setup-ruby@6aaa311d81eba98ae12eaffbcb63296ace0efcde # v1
        with:
          ruby-version: "3.4"

      - name: Install dependencies
        run: |
          npm ci
          bundle install

      # Use the primer GitHub App for authentication.
      # See: https://github.com/organizations/opf/settings/apps/openproject-primer-view-components
      - name: Get App Token
        uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3
        id: get-access-token
        with:
          app-id: ${{ vars.PRIMER_APP_ID_SHARED }}
          owner: opf
          private-key: ${{ secrets.PRIMER_APP_PRIVATE_KEY_SHARED }}
          repositories: |
            primer_view_components

      - name: Create release pull request or publish to npm
        id: changesets
        uses: changesets/action@06245a4e0a36c064a573d4150030f5ec548e4fcc # v1.4.10
        with:
          title: Release Tracking
          version: npm run changeset:version
          publish: script/changeset-publish
        env:
          GITHUB_TOKEN: ${{ steps.get-access-token.outputs.token }}

  release-canary:
    name: Canary
    if: ${{ github.repository == 'opf/primer_view_components' && github.ref_name != 'main' && github.ref_name != 'changeset-release/main' && github.event_name == 'push' }}
    permissions:
      contents: read
      statuses: write
      id-token: write # Required for OIDC
    uses: ./.github/workflows/release_canary.yml
    with:
      install: npm i
    secrets:
      gh_token: ${{ secrets.GITHUB_TOKEN }}

  release-candidate:
    name: Candidate
    if: ${{ github.repository == 'opf/primer_view_components' && github.ref_name == 'changeset-release/main' && github.event_name == 'push' }}
    permissions:
      contents: read
      statuses: write
      id-token: write # Required for OIDC
    uses: ./.github/workflows/release_candidate.yml
    secrets:
      gh_token: ${{ secrets.GITHUB_TOKEN }}
