name: Assign Release Conductor

on:
  pull_request:

jobs:
  pagerduty:
    name: PagerDuty Oncall
    uses: primer/.github/.github/workflows/pagerduty_oncall.yml@release_conductor_script
    with:
      schedule-id: ${{ vars.PAGERDUTY_RELEASE_CONDUCTOR_SCHEDULE }}
    secrets:
      token: ${{ secrets.PAGERDUTY_TOKEN_SHARED }}
  schedule:
    runs-on: ubuntu-latest
    needs: pagerduty
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - run: echo ${{ needs.pagerduty.outputs.user }} is the Release conductor
      - name: Get Release PR
        id: release-pr
        run: |
          echo "assignees=$(gh pr view ${{ github.event.number }} --json assignees --jq ".assignees[].login" | tr '\n' ',' | sed 's/,$//')" >> $GITHUB_OUTPUT
          echo "reviews=$(gh pr view ${{ github.event.number }} --json reviewRequests  --jq ".reviewRequests[].login" | tr '\n' ',' | sed 's/,$//')" >> $GITHUB_OUTPUT
      - name: Reset Assignees & Reviewers
        run: |
          gh pr edit ${{ github.event.number }} --remove-reviewer "${{ steps.release-pr.outputs.reviews }}" --remove-assignee "${{ steps.release-pr.outputs.assignees }}"
          gh pr edit ${{ github.event.number }} --add-reviewer ${{ needs.pagerduty.outputs.user }} --add-assignee ${{ needs.pagerduty.outputs.user }}
