name: Assign Release Conductor

on:
  push:
  workflow_dispatch:

jobs:
  pagerduty:
    name: PagerDuty Oncall
    uses: primer/.github/.github/workflows/pagerduty_oncall.yml@release_conductor_script
    with:
      schedule-id: ${{ vars.PAGERDUTY_RELEASE_CONDUCTOR_SCHEDULE }}
    secrets:
      token: ${{ secrets.PAGERDUTY_TOKEN_SHARED }}
  schedule:
    runs-on: ubuntu-latest
    needs: pagerduty
    steps:
      - run: echo ${{ needs.pagerduty.outputs.user }} is the Release conductor
      - name: Get Release PR
        id: release-pr
        run: |
          PR_NUMBER=$(gh pr list --head changeset-release/main --json number --jq '.[].number')
          echo "number=$PR_NUMBER" >> $GITHUB_OUTPUT
          echo "assignees=$(gh pr view $PR_NUMBER --json assignees --jq ".assignees[].login" | tr '\n' ',' | sed 's/,$//')" >> $GITHUB_OUTPUT
          echo "reviews=$(gh pr view $PR_NUMBER --json reviewRequests  --jq ".reviewRequests[].login" | tr '\n' ',' | sed 's/,$//')" >> $GITHUB_OUTPUT
      - name: Reset Assignees & Reviewers
        run: |
          gh pr edit ${{ steps.release-pr.outputs.number }} --remove-reviewer "${{ steps.release-pr.outputs.reviews }}" --remove-assignee "${{ steps.release-pr.outputs.assignees }}"
          gh pr edit ${{ steps.release-pr.outputs.number }} --add-reviewer ${{ needs.pagerduty.outputs.user }} --add-assignee ${{ needs.pagerduty.outputs.user }}
