name: Release

on:
  workflow_call:
    inputs:
      install:
        type: string
        required: false
        default: npm ci
      tag:
        type: string
        required: false
        default: next
      node_version:
        type: number
        required: false
        default: 24
    secrets:
      gh_token:
        required: true

jobs:
  release-candidate:
    name: Candidate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          # This makes Actions fetch all Git history so that Changesets can generate changelogs with the correct commits
          fetch-depth: 0
          persist-credentials: false

      - name: Set up Node
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
        with:
          node-version: ${{ inputs.node_version }}

      - name: Install dependencies
        run: ${INPUTS_INSTALL}
        env:
          INPUTS_INSTALL: ${{ inputs.install }}

      - name: Build
        run: npm run build --if-present

      - name: Publish release candidate
        run: |
          version=$(jq -r .version package.json)
          echo "$( jq ".version = \"$(echo $version)-rc.$(git rev-parse --short HEAD)\"" package.json )" > package.json
          npx changeset publish --tag ${INPUTS_TAG}
        env:
          GITHUB_TOKEN: ${{ secrets.gh_token }}
          INPUTS_TAG: ${{ inputs.tag }}

      - name: Output candidate version
        uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8
        with:
          script: |
            const package = require(`${process.env.GITHUB_WORKSPACE}/package.json`)
            github.rest.repos.createCommitStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              sha: context.sha,
              state: 'success',
              context: `Published ${package.name}`,
              description: package.version,
              target_url: `https://unpkg.com/${package.name}@${package.version}/`
            })
      # - name: Upload Versions
      #   uses: ./github/.actions/upload-versions/
