name: Ruby on Rails

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rails_version: [5.2.3, 6.0.0, master]
        ruby_version: [2.4.x, 2.5.x, 2.6.x, 2.7.x]
        exclude:
          - rails_version: master
            ruby_version: 2.4.x
          - rails_version: 6.0.0
            ruby_version: 2.4.x
    steps:
    - uses: actions/checkout@master
    - name: Setup Ruby
      uses: actions/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby_version }}
    - name: Update rubygems when testing with Ruby 2.4.x
      if: startsWith(matrix.ruby_version, '2.4')
      run: |
        gem update --system --no-document
    - name: Build primer_view_components
      run: |
        gem install bundler:1.17.3
        bundle update
        bundle install --jobs 4 --retry 3
      env:
        RAILS_VERSION: ${{ matrix.rails_version }}
    - name: Run tests
      run: bundle exec rake
      env:
        RAILS_VERSION: ${{ matrix.rails_version }}
    - name: Run liners
      run: bundle exec rubocop
      env:
        RAILS_VERSION: ${{ matrix.rails_version }}
