name: Generate static files

on:
  workflow_dispatch:
  push:
    branches-ignore:
      - 'dependabot/**'

permissions: {}

jobs:
  static:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3
        id: app-token
        with:
          app-id: ${{ vars.PRIMER_APP_ID_SHARED }}
          private-key: ${{ secrets.PRIMER_APP_PRIVATE_KEY_SHARED }}
          owner: opf
          repositories: primer_view_components
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          token: ${{ steps.app-token.outputs.token }}
          persist-credentials: false
      - uses: ruby/setup-ruby@6aaa311d81eba98ae12eaffbcb63296ace0efcde # v1
        with:
          ruby-version: '3.4'
          bundler-cache: true
      - uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5
        with:
          node-version: 20
          cache: 'npm'
      - name: Build
        run: npm ci
      - name: Generate static files
        run: |
          bundle exec rake utilities:build
          bundle exec rake docs:build
          bundle exec rake static:dump
      - uses: stefanzweifel/git-auto-commit-action@04702edda442b2e678b25b537cec683a1493fcb9 # v7.1.0
        with:
          commit_message: Generating static files
          commit_user_name: OpenProject CI
          commit_user_email: openprojectci@users.noreply.github.com
          commit_author: OpenProject CI <openprojectci@users.noreply.github.com>
          file_pattern: lib/primer/classify/utilities.yml static/*.json
