name: Static Build

on:
  push:
    branches-ignore:
      - main

jobs:
  docs:
    if: ${{ github.actor != 'dependabot[bot]' }}
    name: Docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          token: ${{ secrets.GPR_AUTH_TOKEN_SHARED }}
      - name: Setup Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.7.x
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - run: yarn
      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: gems-build-docs-${{ hashFiles('**/Gemfile.lock') }}
      - name: Generate static files
        run: |
          gem install bundler:2.2.9
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
          bundle exec rake docs:build
        env:
          SKIP_STORYBOOK_PRELOAD: 1
      - name: Commit & Push Docs Data
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "Actions Auto Build"
          git add -f static
          git commit -m "docs: build docs" || true
          git pull --rebase
          git push
  static:
    if: ${{ github.actor != 'dependabot[bot]' }}
    name: Statuses
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          token: ${{ secrets.GPR_AUTH_TOKEN_SHARED }}
      - name: Setup Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.7.x
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - run: yarn
      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: gems-build-docs-${{ hashFiles('**/Gemfile.lock') }}
      - name: Generate static files
        run: |
          gem install bundler:2.2.9
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
          bundle exec rake static:dump
        env:
          SKIP_STORYBOOK_PRELOAD: 1
      - name: Commit & Push Docs Data
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "Actions Auto Build"
          git add -f static
          git commit -m "status: build static files" || true
          git pull --rebase
          git push
  utilities:
    if: ${{ github.actor != 'dependabot[bot]' }}
    name: Utilities
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          token: ${{ secrets.GPR_AUTH_TOKEN_SHARED }}
      - name: Setup Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.7.x
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - run: yarn
      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: gems-build-docs-${{ hashFiles('**/Gemfile.lock') }}
      - name: Generate static files
        run: |
          gem install bundler:2.2.9
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
          bundle exec rake utilities:build
        env:
          SKIP_STORYBOOK_PRELOAD: 1
      - name: Commit & Push Docs Data
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "Actions Auto Build"
          git add -f lib/primer/classify/utilities.yml
          git commit -m "classify: utilities" || true
          git pull --rebase
          git push
  deprecated:
    name: Deprecated components
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Setup Ruby
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 3.0.x
    - name: Make sure deprecated components can be linted
      run: |
        gem install bundler:2.2.9
        bundle config path vendor/bundle
        bundle install --jobs 4 --retry 3
        bundle exec rake static:dump
        bundle exec rake deprecated:check
