name: test-system

on:
  pull_request:
  merge_group:
    branches:
      - main
    types:
      - checks_requested

permissions:
  contents: read

concurrency:
  group: test-system-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  FERRUM_PROCESS_TIMEOUT: 30

jobs:
  system:
    name: System (${{ matrix.browser }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        browser:
          - chrome
          # - firefox  # Firefox is currently disabled due to intermittent CI failures.
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          persist-credentials: false
      - uses: ruby/setup-ruby@6aaa311d81eba98ae12eaffbcb63296ace0efcde # v1
        with:
          ruby-version: "3.2"
          bundler-cache: true
      - uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5
        with:
          node-version: 20
          cache: "npm"
          cache-dependency-path: |
            package-lock.json
            demo/package-lock.json
      - name: Build
        run: |
          npm ci
          cd demo && npm ci
      - name: Test
        run: |
          USE_BROWSER=${{ matrix.browser }} bundle exec rake test:system
