name: test-selectors

on:
  pull_request:

permissions:
  contents: read

concurrency:
  group: test-selectors-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  FERRUM_PROCESS_TIMEOUT: 30

jobs:
  selectors:
    name: CSS coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          persist-credentials: false
      - name: Setup Ruby
        uses: ruby/setup-ruby@6aaa311d81eba98ae12eaffbcb63296ace0efcde # v1
        with:
          ruby-version: "3.2"
          bundler-cache: true
      - name: Setup Node
        uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5
        with:
          node-version: 20
          cache: "npm"
      - name: NPM Build
        run: npm ci
        env:
          # Disable CSS minification for tests
          CI: "false"
      - name: Test CSS
        run: bundle exec rake test:component_css
