name: Test token action

on:
  push:
    branches:
      - '*'

jobs:
  get-token:
    runs-on: ubuntu-latest
    steps:
      - id: get-token
        uses: camertron/github-app-installation-auth-action@v1
        with:
          app-id: ${{ vars.PRIMER_APP_ID_SHARED }}
          private-key: ${{ secrets.PRIMER_APP_PRIVATE_KEY_SHARED }}
          client-id: ${{ vars.PRIMER_APP_CLIENT_ID_SHARED }}
          client-secret: ${{ secrets.PRIMER_APP_CLIENT_SECRET_SHARED }}
          installation-id: ${{ vars.PRIMER_APP_INSTALLATION_ID_SHARED }}
      - uses: actions/checkout@v3
        with:
          token: ${{ steps.get-token.outputs.access-token }}
