- button "Comment ( )": Comment ()
- text: light
- button "Comment ( )": Comment ()
- text: light_colorblind
- button "Comment ( )": Comment ()
- text: light_high_contrast
- button "Comment ( )": Comment ()
- text: dark
- button "Comment ( )": Comment ()
- text: dark_dimmed
- button "Comment ( )": Comment ()
- text: dark_high_contrast
- button "Comment ( )": Comment ()
- text: dark_colorblind