- text: First name
- textbox "First name First name First name First name First name First name First name"
- text: What your friends call you. Last name
- textbox "Last name Last name Last name Last name Last name Last name Last name"
- text: What the principal calls you. Dietary restrictions
- textbox "Dietary restrictions Dietary restrictions Dietary restrictions Dietary restrictions Dietary restrictions Dietary restrictions Dietary restrictions"
- text: Any allergies?
- checkbox "Send me gobs of email! Send me gobs of email! Send me gobs of email! Send me gobs of email! Send me gobs of email! Send me gobs of email! Send me gobs of email!": "1"
- text: Send me gobs of email! Check this if you enjoy getting spam. light First name
- textbox
- text: What your friends call you. Last name
- textbox
- text: What the principal calls you. Dietary restrictions
- textbox
- text: Any allergies?
- checkbox: "1"
- text: Send me gobs of email! Check this if you enjoy getting spam. light_colorblind First name
- textbox
- text: What your friends call you. Last name
- textbox
- text: What the principal calls you. Dietary restrictions
- textbox
- text: Any allergies?
- checkbox: "1"
- text: Send me gobs of email! Check this if you enjoy getting spam. light_high_contrast First name
- textbox
- text: What your friends call you. Last name
- textbox
- text: What the principal calls you. Dietary restrictions
- textbox
- text: Any allergies?
- checkbox: "1"
- text: Send me gobs of email! Check this if you enjoy getting spam. dark First name
- textbox
- text: What your friends call you. Last name
- textbox
- text: What the principal calls you. Dietary restrictions
- textbox
- text: Any allergies?
- checkbox: "1"
- text: Send me gobs of email! Check this if you enjoy getting spam. dark_dimmed First name
- textbox
- text: What your friends call you. Last name
- textbox
- text: What the principal calls you. Dietary restrictions
- textbox
- text: Any allergies?
- checkbox: "1"
- text: Send me gobs of email! Check this if you enjoy getting spam. dark_high_contrast First name
- textbox
- text: What your friends call you. Last name
- textbox
- text: What the principal calls you. Dietary restrictions
- textbox
- text: Any allergies?
- checkbox: "1"
- text: Send me gobs of email! Check this if you enjoy getting spam. dark_colorblind